<?php
//支付方式 配置文件
return  array(
	array( // row #0
		'id' => 0,
		'name' => '货到付款',
		'type' => 2,
		'class_name' => 'freight_collect',
		'description' => '货到付款',
		'logo' => '/payments/logos/pay_freight_collect.jpg',
		'status' => 1,
		'order' => 99,
		'note' => NULL,
		'poundage' => 0.00,
		'poundage_type' => 1,
		'config_param' => NULL,
		'client_type' => 3,
	),
	array( // row #1
		'id' => 1,
		'name' => '预存款',
		'type' => 1,
		'class_name' => 'balance',
		'description' => '预存款是客户在您网站上的虚拟资金帐户。',
		'logo' => '/payments/logos/pay_deposit.gif',
		'status' => 0,
		'order' => 99,
		'note' => NULL,
		'poundage' => 0.00,
		'poundage_type' => 1,
		'config_param' => NULL,
		'client_type' => 3,
	),
	array( // row #2
		'id' => 2,
		'name' => '网银在线',
		'type' => 1,
		'class_name' => 'chinabank',
		'description' => '网银在线是中国领先的电子支付解决方案提供商之一。 <a href="http://www.chinabank.com.cn/" target="_blank">立即申请</a>',
		'logo' => '/payments/logos/pay_chinabank.gif',
		'status' => 1,
		'order' => 99,
		'note' => NULL,
		'poundage' => 0.00,
		'poundage_type' => 1,
		'config_param' => NULL,
		'client_type' => 1,
	),
	array( // row #3
		'id' => 3,
		'name' => '腾讯财付通',
		'type' => 1,
		'class_name' => 'tenpay',
		'description' => '财付通是腾讯公司创办的中国领先的在线支付平台，致力于为互联网用户和企业提供安全、便捷、专业的在线支付服务。 <a href="https://www.tenpay.com/v2/" target="_blank">立即申请</a>',
		'logo' => '/payments/logos/pay_tenpay.gif',
		'status' => 1,
		'order' => 99,
		'note' => NULL,
		'poundage' => 0.00,
		'poundage_type' => 1,
		'config_param' => NULL,
		'client_type' => 1,
	),
	array( // row #4
		'id' => 4,
		'name' => '快钱',
		'type' => 1,
		'class_name' => 'bill99',
		'description' => '快钱是国内领先的独立第三方支付企业，旨在为各类企业及个人提供安全、便捷和保密的支付清算与账务服务。 <a href="https://www.99bill.com/" target="_blank">立即申请</a>',
		'logo' => '/payments/logos/pay_99bill.gif',
		'status' => 1,
		'order' => 99,
		'note' => NULL,
		'poundage' => 0.00,
		'poundage_type' => 1,
		'config_param' => NULL,
		'client_type' => 1,
	),
	array( // row #5
		'id' => 5,
		'name' => '支付宝担保交易',
		'type' => 1,
		'class_name' => 'trade_alipay',
		'description' => '担保交易支付方式，淘宝买家最熟悉的付款方式：买家先将交易资金存入支付宝并通知卖家发货，买家确认收货后资金自动进入卖家支付宝账户，完成交易。 <a href="http://www.alipay.com/" target="_blank">立即申请</a>',
		'logo' => '/payments/logos/pay_alipay.gif',
		'status' => 1,
		'order' => 99,
		'note' => NULL,
		'poundage' => 0.00,
		'poundage_type' => 1,
		'config_param' => NULL,
		'client_type' => 1,
	),
	array( // row #6
		'id' => 6,
		'name' => '支付宝即时到帐',
		'type' => 1,
		'class_name' => 'direct_alipay',
		'description' => '即时到帐支付方式，网上交易时，买家的交易资金直接打入卖家支付宝账户，快速回笼交易资金。 <a href="http://www.alipay.com/" target="_blank">立即申请</a>',
		'logo' => '/payments/logos/pay_alipay.gif',
		'status' => 1,
		'order' => 99,
		'note' => NULL,
		'poundage' => 0.00,
		'poundage_type' => 1,
		'config_param' => '{"M_PartnerId":"2088611496883972","M_PartnerKey":"asfl3i2s32bbkbedfc1zpxivbvsmegbq","M_Email":"liudunming@zhagen.com"}',
		'client_type' => 1,
	),
	array( // row #7
		'id' => 7,
		'name' => '支付宝双接口',
		'type' => 1,
		'class_name' => 'alipay',
		'description' => '担保+即使双接口支付方式，给于买家充足的自主选择权。 <a href="http://www.alipay.com/" target="_blank">立即申请</a>',
		'logo' => '/payments/logos/pay_alipay.gif',
		'status' => 0,
		'order' => 99,
		'note' => NULL,
		'poundage' => 0.00,
		'poundage_type' => 1,
		'config_param' => NULL,
		'client_type' => 1,
	),
	array( // row #8
		'id' => 8,
		'name' => '贝宝',
		'type' => 1,
		'class_name' => 'paypal',
		'description' => '是全球最大的在线支付平台，同时也是目前全球贸易网上支付标准。<a href="https://www.paypal-biz.com/" target="_blank">立即申请</a>',
		'logo' => '/payments/logos/pay_paypal.gif',
		'status' => 1,
		'order' => 99,
		'note' => NULL,
		'poundage' => 0.00,
		'poundage_type' => 1,
		'config_param' => NULL,
		'client_type' => 1,
	),
	array( // row #9
		'id' => 9,
		'name' => '微信扫一扫',
		'type' => 1,
		'class_name' => 'wechat',
		'description' => '微信扫一扫支付接口。<a href="https://www.swiftpass.cn" target="_blank">立即申请</a>',
		'logo' => '/payments/logos/pay_wechat.gif',
		'status' => 0,
		'order' => 1,
		'note' => '微信支付',
		'poundage' => 0.00,
		'poundage_type' => 1,
		'config_param' => '{"M_PartnerId":"ssss","M_PartnerKey":"ssssssss"}',
		'client_type' => 1,
	),
	array( // row #10
		'id' => 10,
		'name' => '线下支付',
		'type' => 2,
		'class_name' => 'offline',
		'description' => '线下付款结算',
		'logo' => '/payments/logos/pay_offline.gif',
		'status' => 1,
		'order' => 99,
		'note' => NULL,
		'poundage' => 0.00,
		'poundage_type' => 0,
		'config_param' => NULL,
		'client_type' => 3,
	),
	array( // row #11
		'id' => 11,
		'name' => '银信证',
		'type' => 1,
		'class_name' => 'cipay',
		'description' => '银信证支付',
		'logo' => '/payments/logos/pay_cipay.jpg',
		'status' => 1,
		'order' => 99,
		'note' => NULL,
		'poundage' => 0.00,
		'poundage_type' => 0,
		'config_param' => NULL,
		'client_type' => 1,
	),
	array( // row #12
		'id' => 12,
		'name' => '支付宝移动支付',
		'type' => 1,
		'class_name' => 'wap_alipay',
		'description' => '手机支付方便用户手机快速下单。 <a href="http://www.alipay.com/" target="_blank">立即申请</a>',
		'logo' => '/payments/logos/pay_wap_alipay.png',
		'status' => 0,
		'order' => 99,
		'note' => NULL,
		'poundage' => 0.00,
		'poundage_type' => 1,
		'config_param' => NULL,
		'client_type' => 2,
	),
);
?>